language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - FLAGS=
  - FLAGS=--glottolog-tag=master
jobs:
  exclude:
    - python: 3.6
      env: FLAGS=--glottolog-tag=master
    - python: 3.7
      env: FLAGS=--glottolog-tag=master
cache: pip
before_cache: rm -f $HOME/.cache/pip/log/debug.log
install: pip install .[test,pretty,pandas] codecov
script: ./run-tests.py --loglevel-debug $FLAGS
after_success: codecov
