version: ~> 1.0
dist: focal
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  - FLAGS=
  - FLAGS=--run-writes
  - FLAGS=--glottolog-tag=master
jobs:
  exclude:
    - python: 3.6
      env: FLAGS=--run-writes
    - python: 3.7
      env: FLAGS=--run-writes
    - python: 3.8
      env: FLAGS=--run-writes
    - python: 3.6
      env: FLAGS=--glottolog-tag=master
    - python: 3.7
      env: FLAGS=--glottolog-tag=master
    - python: 3.8
      env: FLAGS=--glottolog-tag=master
    - python: 3.9
      env: FLAGS=
install: pip install .[test,pretty,pandas] codecov
script: ./run-tests.py --loglevel-debug $FLAGS
before_cache: rm -f $HOME/.cache/pip/log/debug.log
after_success: codecov
