language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - ARGS=
  - ARGS=--glottolog-tag=master
jobs:
  exclude:
    - python: 3.6
      env: ARGS=--glottolog-tag=master
    - python: 3.7
      env: ARGS=--glottolog-tag=master
cache: pip
before_cache: rm -f $HOME/.cache/pip/log/debug.log
install: pip install .[test,pretty] codecov
script: ./run-tests.py $ARGS
after_success: codecov
