version: ~> 1.0
dist: focal
language: python
cache: pip
python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
env:
  - ARGS=--run-writes
  - ARGS=--glottolog-tag=master
  - ARGS=
jobs:
  exclude:
    - python: 3.9
      env: ARGS=
    - python: 3.8
      env: ARGS=--run-writes
    - python: 3.7
      env: ARGS=--run-writes
    - python: 3.6
      env: ARGS=--run-writes
    - python: 3.8
      env: ARGS=--glottolog-tag=master
    - python: 3.7
      env: ARGS=--glottolog-tag=master
    - python: 3.6
      env: ARGS=--glottolog-tag=master
install: pip install .[test,pretty,pandas] codecov
script: ./run-tests.py --loglevel-debug $ARGS
before_cache: rm -f $HOME/.cache/pip/log/debug.log
after_success: codecov
